# Generated by Django 4.2 on 2025-02-08 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('release_year', models.DateField()),
                ('gender', models.CharField(choices=[('ROCK', 'Rock'), ('POP', 'Pop'), ('RAP', 'Rap'), ('JAZZ', 'Jazz'), ('BLUES', 'Blues'), ('REGGAE', 'Reggae'), ('METAL', 'Metal'), ('CLÁSICA', 'Clásica'), ('ELECTRONICA', 'Electronica'), ('OTRO', 'Otro')], max_length=20)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='album_manager.artist')),
            ],
        ),
    ]
